
runtime: python39
instance_class: F1

automatic_scaling:
  target_cpu_utilization: 0.65
  min_instances: 1
  max_instances: 3

env_variables:
  CLOUD_SQL_CONNECTION_NAME: "student-analytics-project:us-central1:student-performance-db"

handlers:
- url: /static
  static_dir: static
  
- url: /.*
  script: auto
